import { v4 as uuid } from "uuid";

export const books = [
  {
    _id: uuid(),
    title: "Harry Potter Complete Set",
    author: "J.K. Rowling",
    bookImg:
      "https://res.cloudinary.com/ddqytua2y/image/upload/v1687012694/Bookshelf-app/uwsk8djwl29i9lxjs1v1.jpg",
    category: "read",
  },
  {
    _id: uuid(),
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687012886/Bookshelf-app/81r81MTfTuL._AC_UF1000_1000_QL80__eaiqoc.jpg",
    category: "read",
  },
  {
    _id: uuid(),
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687012926/Bookshelf-app/61z0MrB6qOS._AC_UL600_SR600_600__glwggh.jpg",
    category: "want-to-read",
  },
  {
    _id: uuid(),
    title: "Pride and Prejudice",
    author: "Jane Austen",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687012961/Bookshelf-app/PrideAndPrejudiceTitlePage_jbwafq.jpg",
    category: "read",
  },
  {
    _id: uuid(),
    title: "1984",
    author: "George Orwell",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013055/Bookshelf-app/41nGXlJ2GSL_ojmaqg.jpg",
    category: "currently-reading",
  },
  {
    _id: uuid(),
    title: "To the Lighthouse",
    author: "Virginia Woolf",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013108/Bookshelf-app/51XUmAPaXUL_y5ky9r.jpg",
    category: "want-to-read",
  },
  {
    _id: uuid(),
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013153/Bookshelf-app/91HPG31dTwL._AC_UF1000_1000_QL80__x1fmay.jpg",
    category: "currently-reading",
  },
  {
    _id: uuid(),
    title: "Moby-Dick",
    author: "Herman Melville",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013183/Bookshelf-app/41VnFKC9srL._AC_UF1000_1000_QL80__md5nhx.jpg",
    category: "currently-reading",
  },
  {
    _id: uuid(),
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013213/Bookshelf-app/710_HcoP38L._AC_UF1000_1000_QL80__rt1efr.jpg",
    category: "want-to-read",
  },
  {
    _id: uuid(),
    title: "Brave New World",
    author: "Aldous Huxley",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013243/Bookshelf-app/914u_JexlCL._AC_UF1000_1000_QL80__culi80.jpg",
    category: "none",
  },
  {
    _id: uuid(),
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013273/Bookshelf-app/71jLBXtWJWL._AC_UF1000_1000_QL80__olhx3v.jpg",
    category: "none",
  },
  {
    _id: uuid(),
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    bookImg: "https://res.cloudinary.com/ddqytua2y/image/upload/v1687013337/Bookshelf-app/41k-X9hJ5HL_bg67vk.jpg",
    category: "none",
  },
//   {
//     _id: uuid(),
//     title: "Gone with the Wind",
//     author: "Margaret Mitchell",
//     bookImg: "",
//     category: "none",
//   },
//   {
//     _id: uuid(),
//     title: "Jane Eyre",
//     author: "Charlotte Brontë",
//     bookImg: "",
//     category: "none",
//   },
//   {
//     _id: uuid(),
//     title: "The Odyssey",
//     author: "Homer",
//     bookImg: "",
//     category: "none",
//   },
//   {
//     _id: uuid(),
//     title: "The Picture of Dorian Gray",
//     author: "Oscar Wilde",
//     bookImg: "",
//     category: "none",
//   },
];
